fov: 200          # FOV AÚN MÁS PEQUEÑO para mayor precisión
speed: 0.8        # VELOCIDAD MÁS LENTA y controlada
enable_y_axis: true  # MOVIMIENTO VERTICAL
# AZULES CLARITOS (más específicos para mayor precisión):
hsv_lower: [95, 80, 120]    # Rangos más estrictos
hsv_upper: [115, 255, 255]  # Menos amplio, más preciso